spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/mybbs?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false 
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
    
banner:
  location: banner.txt
site:
  name: 朋也社区
  baseUrl: http://localhost:8080/
  sessionName: _user
  adminSessionName: _admin_user
  cookieName: _token
  adminCookieName: _admin_token
  cookieDomain: localhost
  cookieExpireTime: 30
  pageSize: 20
  avatarPath: C:\tmp\cms7\nas\avatar\ 
  uploadPath: C:\tmp\cms7\nas\upload\
  sections:
  - 分享
  - 问答
  - 新闻
  - 博客
  - 招聘
  theme: bootstrap